import Foundation

/// The Vault — the human escape hatch (SPEC §6.1): a read-only markdown
/// mirror, greppable and Obsidian-openable, regenerated by the fold, never
/// watched. At M0 it renders journal day files (captures + transcripts);
/// entity files arrive with the Graph in M2.
///
/// Sanctum events render under the hidden `.sanctum/` dot-directory — which
/// Spotlight does not index (the §6.1 mechanism) and which the Vault's git
/// repo ignores, so Sanctum plaintext never enters git history and erasure
/// stays file-delete + refold (plan U7). Empty until the Sanctum gesture
/// unlocks in a later milestone.
public struct VaultLens: Lens {
    public let name = "vault"
    /// Fold parameters are part of the version: a timezone change or format
    /// change rebuilds from genesis (R3).
    public let viewVersion = "vault-v1;tz=\(FirmamentTime.dayBucketTimeZoneID)"

    public let root: URL
    public let gitEnabled: Bool

    public var journalDirectory: URL { root.appendingPathComponent("journal", isDirectory: true) }
    public var sanctumDirectory: URL {
        root.appendingPathComponent(".sanctum", isDirectory: true)
            .appendingPathComponent("journal", isDirectory: true)
    }

    public init(root: URL, gitEnabled: Bool = true) throws {
        self.root = root
        self.gitEnabled = gitEnabled
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        if gitEnabled {
            try Self.ensureGitRepo(at: root)
        }
    }

    // MARK: Lens

    public func fold(new: [Event], all: [Event]) throws {
        let byID = Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })
        var affectedDays = Set<String>()

        func noteAffected(_ event: Event) {
            switch event.kind {
            case .captureText, .captureAudio:
                affectedDays.insert(FirmamentTime.dayString(epochMS: event.occurredAt))
            case .transcript:
                if let parent = event.parentID.flatMap({ byID[$0] }) {
                    affectedDays.insert(FirmamentTime.dayString(epochMS: parent.occurredAt))
                }
            case .tombstone:
                guard let payload = try? TombstonePayload(canonical: event.decodedPayload()) else { return }
                for target in payload.targets {
                    if let targetEvent = byID[target] {
                        noteAffected(targetEvent)
                    }
                }
            default:
                break
            }
        }

        for event in new {
            noteAffected(event)
        }
        guard !affectedDays.isEmpty else { return }
        try render(days: affectedDays, all: all)
        if gitEnabled {
            try Self.commitIfChanged(at: root, message: "fold: \(new.count) event(s)")
        }
    }

    public func reset() throws {
        try? FileManager.default.removeItem(at: journalDirectory)
        try? FileManager.default.removeItem(at: sanctumDirectory)
    }

    // MARK: Rendering

    private func render(days: Set<String>, all: [Event]) throws {
        let tombstoned = Self.tombstonedIDs(all)
        let transcriptsByParent = Dictionary(
            grouping: all.filter { $0.kind == .transcript && !tombstoned.contains($0.id) },
            by: { $0.parentID }
        )

        let visibleCaptures = all.filter { event in
            (event.kind == .captureText || event.kind == .captureAudio)
                && !tombstoned.contains(event.id)
        }
        let byDay = Dictionary(grouping: visibleCaptures) {
            FirmamentTime.dayString(epochMS: $0.occurredAt)
        }

        for day in days.sorted() {
            let captures = (byDay[day] ?? []).sorted {
                ($0.occurredAt, $0.id.uuidString) < ($1.occurredAt, $1.id.uuidString)
            }
            for sanctum in [false, true] {
                let selected = captures.filter { ($0.tier == .sanctum) == sanctum }
                let directory = sanctum ? sanctumDirectory : journalDirectory
                let file = directory.appendingPathComponent("\(day).md")
                if selected.isEmpty {
                    try? FileManager.default.removeItem(at: file)
                    continue
                }
                try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
                let content = Self.renderDay(day, captures: selected, transcriptsByParent: transcriptsByParent)
                try Data(content.utf8).write(to: file, options: .atomic)
            }
        }
    }

    static func tombstonedIDs(_ all: [Event]) -> Set<UUID> {
        var hidden = Set<UUID>()
        for event in all where event.kind == .tombstone {
            guard let payload = try? TombstonePayload(canonical: event.decodedPayload()) else { continue }
            hidden.formUnion(payload.targets)
        }
        return hidden
    }

    static func renderDay(
        _ day: String,
        captures: [Event],
        transcriptsByParent: [UUID?: [Event]]
    ) -> String {
        var lines = [String]()
        lines.append("---")
        lines.append("day: \(day)")
        lines.append("tz: \(FirmamentTime.dayBucketTimeZoneID)")
        lines.append("events:")
        for capture in captures {
            lines.append("  - \(capture.id.uuidString.lowercased())")
        }
        lines.append("---")
        for capture in captures {
            lines.append("")
            let time = FirmamentTime.timeString(epochMS: capture.occurredAt)
            switch capture.kind {
            case .captureAudio:
                lines.append("## \(time) · voice")
                lines.append("<!-- event:\(capture.id.uuidString.lowercased()) -->")
                lines.append("")
                if let transcript = selectTranscript(for: capture, in: transcriptsByParent),
                   let payload = try? TranscriptPayload(canonical: transcript.decodedPayload()) {
                    lines.append(payload.text)
                } else {
                    lines.append("*awaiting transcription*")
                }
            default:
                lines.append("## \(time) · note")
                lines.append("<!-- event:\(capture.id.uuidString.lowercased()) -->")
                lines.append("")
                if let payload = try? CaptureTextPayload(canonical: capture.decodedPayload()) {
                    lines.append(payload.body)
                }
            }
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Multi-transcript dedup rule (plan U7): prefer the transcript whose
    /// device matches the capture's device, else the earliest by id.
    static func selectTranscript(for capture: Event, in byParent: [UUID?: [Event]]) -> Event? {
        guard let candidates = byParent[capture.id], !candidates.isEmpty else { return nil }
        let sorted = candidates.sorted { $0.id.uuidString < $1.id.uuidString }
        return sorted.first { $0.deviceID == capture.deviceID } ?? sorted.first
    }

    // MARK: Git (Mac-only; the phone never materializes — SPEC §5.5)

    static func ensureGitRepo(at root: URL) throws {
        #if os(macOS)
        let gitDir = root.appendingPathComponent(".git")
        let ignore = root.appendingPathComponent(".gitignore")
        if !FileManager.default.fileExists(atPath: ignore.path) {
            try Data(".sanctum/\n.DS_Store\n".utf8).write(to: ignore)
        }
        if !FileManager.default.fileExists(atPath: gitDir.path) {
            try run(["git", "init", "-q"], in: root)
            try run(["git", "config", "user.name", "Firmament"], in: root)
            try run(["git", "config", "user.email", "vault@firmament.local"], in: root)
        }
        #endif
    }

    static func commitIfChanged(at root: URL, message: String) throws {
        #if os(macOS)
        let status = try run(["git", "status", "--porcelain"], in: root)
        guard !status.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        try run(["git", "add", "-A"], in: root)
        try run(["git", "commit", "-q", "-m", message], in: root)
        #endif
    }

    #if os(macOS)
    @discardableResult
    static func run(_ arguments: [String], in directory: URL) throws -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = arguments
        process.currentDirectoryURL = directory
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        try process.run()
        process.waitUntilExit()
        let output = String(decoding: pipe.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self)
        guard process.terminationStatus == 0 else {
            throw VaultError.gitFailed(command: arguments.joined(separator: " "), output: output)
        }
        return output
    }
    #endif

    public enum VaultError: Error {
        case gitFailed(command: String, output: String)
    }
}
